/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.NGO;

import Business.WorkQueue.DonationRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Pratik Gawand
 */
public class ProcessDonationRequest extends javax.swing.JPanel {

    /**
     * Creates new form ProcessDonationRequest
     */
    private JPanel userProcessContainer;
    private DonationRequest request;

    public ProcessDonationRequest(JPanel userProcessContainer, DonationRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        groupButton();
    }

    private void groupButton() {

        ButtonGroup bg1 = new ButtonGroup();
        bg1.add(rdApprovedCheck);
        bg1.add(rdRejectedCheck);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rdRejectedCheck = new javax.swing.JRadioButton();
        rdApprovedCheck = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setForeground(new java.awt.Color(204, 204, 204));
        setLayout(null);

        btnSubmit.setBackground(new java.awt.Color(153, 153, 153));
        btnSubmit.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit Result");
        btnSubmit.setAlignmentX(0.5F);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit);
        btnSubmit.setBounds(570, 320, 137, 27);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 0));
        jLabel1.setText("Result:");
        add(jLabel1);
        jLabel1.setBounds(680, 200, 60, 23);

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setAlignmentX(0.5F);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(830, 320, 137, 27);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 0));
        jLabel2.setText("Processing Request");
        add(jLabel2);
        jLabel2.setBounds(680, 160, 194, 30);

        rdRejectedCheck.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        rdRejectedCheck.setText("Rejected");
        add(rdRejectedCheck);
        rdRejectedCheck.setBounds(750, 240, 72, 23);

        rdApprovedCheck.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        rdApprovedCheck.setText("Approved");
        add(rdApprovedCheck);
        rdApprovedCheck.setBounds(750, 200, 74, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Resources/ngo2.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(360, 50, 810, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        if (rdApprovedCheck.isSelected()) {
            // request.setRequestResult("Approved");
            request.setStatus("Completed");
            JOptionPane.showMessageDialog(null, "Request Approved!");

        } else if (rdRejectedCheck.isSelected()) {
            // request.setRequestResult("Rejected");
            request.setStatus("Rejected");
            JOptionPane.showMessageDialog(null, "Request Rejected!");
        } else if (!(rdApprovedCheck.isSelected()) && !(rdRejectedCheck.isSelected())) {

            JOptionPane.showMessageDialog(null, "Please select a result!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        NGODashboardJpanel ngodj = (NGODashboardJpanel) component;
        ngodj.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rdApprovedCheck;
    private javax.swing.JRadioButton rdRejectedCheck;
    // End of variables declaration//GEN-END:variables
}
