/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Distributor;

import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author satwi
 */
public class ProcessWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessWorkAreaJPanel
     */
    public ProcessWorkAreaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProcessRequest = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProcessRequest = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();
        lblInventoryDashboard = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnProductType = new javax.swing.JButton();
        btnInventoryCount = new javax.swing.JButton();
        lblFilter = new javax.swing.JLabel();
        lblCount = new javax.swing.JLabel();
        cmbProductTpe = new javax.swing.JComboBox<>();
        btnRequestSupplier = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtComments = new javax.swing.JTextPane();
        lblComments = new javax.swing.JLabel();
        btnApprove = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(null);

        lblProcessRequest.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblProcessRequest.setText("Process Request");
        add(lblProcessRequest);
        lblProcessRequest.setBounds(178, 52, 140, 23);

        tblProcessRequest.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tblProcessRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product Type", "Product", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(tblProcessRequest);

        add(jScrollPane1);
        jScrollPane1.setBounds(6, 87, 1467, 106);

        tblInventory.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID ", "Product Type", "Product Name", "Availability", "Units"
            }
        ));
        jScrollPane2.setViewportView(tblInventory);

        add(jScrollPane2);
        jScrollPane2.setBounds(0, 380, 1467, 106);

        lblInventoryDashboard.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblInventoryDashboard.setText("Inventory Dashboard");
        add(lblInventoryDashboard);
        lblInventoryDashboard.setBounds(150, 320, 160, 23);

        btnBack.setBackground(java.awt.SystemColor.activeCaption);
        btnBack.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.setAlignmentX(0.5F);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(1330, 20, 72, 21);

        btnProductType.setBackground(java.awt.SystemColor.activeCaption);
        btnProductType.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnProductType.setText("Product Type");
        add(btnProductType);
        btnProductType.setBounds(160, 350, 98, 21);

        btnInventoryCount.setBackground(java.awt.SystemColor.activeCaption);
        btnInventoryCount.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnInventoryCount.setText("Inventory Count");
        btnInventoryCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryCountActionPerformed(evt);
            }
        });
        add(btnInventoryCount);
        btnInventoryCount.setBounds(270, 350, 114, 21);

        lblFilter.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblFilter.setText("Filter:");
        add(lblFilter);
        lblFilter.setBounds(10, 350, 50, 18);
        add(lblCount);
        lblCount.setBounds(530, 350, 937, 22);

        cmbProductTpe.setBackground(java.awt.SystemColor.activeCaption);
        cmbProductTpe.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cmbProductTpe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbProductTpe);
        cmbProductTpe.setBounds(80, 350, 69, 21);

        btnRequestSupplier.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnRequestSupplier.setText("Request Supplier");
        add(btnRequestSupplier);
        btnRequestSupplier.setBounds(590, 570, 140, 24);

        jScrollPane3.setViewportView(txtComments);

        add(jScrollPane3);
        jScrollPane3.setBounds(580, 500, 284, 22);

        lblComments.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblComments.setText("Comments:");
        add(lblComments);
        lblComments.setBounds(510, 510, 70, 18);

        btnApprove.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnApprove.setText("Approve");
        add(btnApprove);
        btnApprove.setBounds(750, 570, 116, 24);

        jLabel1.setIcon(new ImageIcon(new ImageIcon("C:\\Users\\bhagy\\OneDrive\\Documents\\NetBeansProjects\\AED_Final_Bhagyashree\\AED_Final_Project\\process.png").getImage().getScaledInstance(75, 75, Image.SCALE_DEFAULT)));
        add(jLabel1);
        jLabel1.setBounds(6, 0, 75, 75);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Resources/inventory2-compressed.jpg"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(590, 190, 260, 200);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
//        userProcessContainer.remove(this);
//        Component[] componentArray = userProcessContainer.getComponents();
//        Component component = componentArray[componentArray.length - 1];
//        DistributorDashboardJpanel ddj = (DistributorDashboardJpanel) component;
//        ddj.populateTable();
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnInventoryCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventoryCountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnInventoryCount;
    private javax.swing.JButton btnProductType;
    private javax.swing.JButton btnRequestSupplier;
    private javax.swing.JComboBox<String> cmbProductTpe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblComments;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lblFilter;
    private javax.swing.JLabel lblInventoryDashboard;
    private javax.swing.JLabel lblProcessRequest;
    private javax.swing.JTable tblInventory;
    private javax.swing.JTable tblProcessRequest;
    private javax.swing.JTextPane txtComments;
    // End of variables declaration//GEN-END:variables
}
