/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.Orphange;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.OrphanageOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DonationRequest;
import Business.WorkQueue.Need;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sathwik
 */
public class OrphanageDashboardJpanel extends javax.swing.JPanel {

    /**
     * Creates new form OrphanageDashboardJpanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private OrphanageOrganization orphanageOrganization;
    private Enterprise enterprise;
    private EcoSystem business;

    public OrphanageDashboardJpanel(JPanel userProcessContainer, UserAccount userAccount, OrphanageOrganization orphanageOrganization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.orphanageOrganization = orphanageOrganization;
        this.business = business;
        lblEnterpriseValue.setText(enterprise.getName());
        populateRequestTable();
        //   populateData();
    }

    public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) tblDonationReq.getModel();

        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {

            // if (productList!=null){
            //for (Products p : productList) {
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getReceiver();
            row[2] = request.getStatus();
            String result = ((DonationRequest) request).getStatus();
            row[3] = result == null ? "Waiting" : result;

            model.addRow(row);

        }

    }

    //adding below method to get product data
    public void populateData() {

        DefaultTableModel model = (DefaultTableModel) tblNeeds.getModel();

        model.setRowCount(0);
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
            ArrayList<Need> needList = ((DonationRequest) request).getNeedList();
            if (needList != null) {
                for (Need n : needList) {
                    Object row[] = new Object[3];
                    row[0] = n;
                    row[1] = n.getNeedName();
                    row[2] = n.getQuantity();
                    ((DefaultTableModel) tblNeeds.getModel()).addRow(row);
                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEnterprise = new javax.swing.JLabel();
        lblEnterpriseValue = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDonationReq = new javax.swing.JTable();
        btnRequestDonation = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNeeds = new javax.swing.JTable();
        btnShowNeeds = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        lblEnterprise.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblEnterprise.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEnterprise.setText("Enterprise:");

        lblEnterpriseValue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnRefresh.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnRefresh.setText("Refresh");

        tblDonationReq.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tblDonationReq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Request Name", "Receiver", "Status", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDonationReq);

        btnRequestDonation.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnRequestDonation.setText("New Request");
        btnRequestDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestDonationActionPerformed(evt);
            }
        });

        tblNeeds.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tblNeeds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Type", "Product", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblNeeds);

        btnShowNeeds.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnShowNeeds.setText("Display Products");
        btnShowNeeds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowNeedsActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Resources/donate5.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setText("View Requests");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnShowNeeds, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnRequestDonation, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEnterprise)
                            .addComponent(lblEnterpriseValue, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh)
                        .addGap(102, 102, 102)))
                .addGap(261, 261, 261))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnRequestDonation, btnShowNeeds});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRefresh)
                    .addComponent(lblEnterpriseValue, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRequestDonation)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnShowNeeds)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnRequestDonation, btnShowNeeds});

    }// </editor-fold>//GEN-END:initComponents

    private void btnShowNeedsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowNeedsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDonationReq.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a request");
        }

        DefaultTableModel model = (DefaultTableModel) tblNeeds.getModel();
        model.setRowCount(0);
        model.setRowCount(0);
        WorkRequest request = (WorkRequest) tblDonationReq.getValueAt(selectedRow, 0);

        ArrayList<Need> needList = ((DonationRequest) request).getNeedList();
        if (needList != null) {
            for (Need n : needList) {
                Object row[] = new Object[3];
                row[0] = n;
                row[1] = n.getNeedName();
                row[2] = n.getQuantity();
                ((DefaultTableModel) tblNeeds.getModel()).addRow(row);
            }
        }
    }//GEN-LAST:event_btnShowNeedsActionPerformed

    private void btnRequestDonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestDonationActionPerformed
        // TODO add your handling code here:

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestItemsJPanel", new RequestItemsJPanel(userProcessContainer, userAccount, enterprise, business));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRequestDonationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRequestDonation;
    private javax.swing.JButton btnShowNeeds;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblEnterpriseValue;
    private javax.swing.JTable tblDonationReq;
    private javax.swing.JTable tblNeeds;
    // End of variables declaration//GEN-END:variables
}
